### ISSUE TITLE
no result found

### ISSUE THREAD

**Issue by melbasuonyy** [SafwanLjd/EgyBestCLI#1]
Hi 
I'm getting the below error 
![Screenshot 2022-01-13 220445](https://user-images.githubusercontent.com/29347988/149384862-4d765d0a-f6dc-4b5b-9400-e34d4296e3b6.png)

**Comment by SafwanLjd** [comment]
This is an EgyBest issue, it sometimes breaks… you can confirm this by searching something manually on EgyBest, you'll get no results there as well

**Comment by melbasuonyy** [comment]
can you tell which url is used egy.best is blocked by ISP - but egybest.org is ok

**Comment by melbasuonyy** [comment]
![Screenshot 2022-01-13 222614](https://user-images.githubusercontent.com/29347988/149387856-2ee709fc-da8d-488b-af04-197a8901d0d1.png)
Movie is available in egybest search

**Comment by SafwanLjd** [comment]
I will investigate the issue

**Comment by SafwanLjd** [comment]
I have just investigated the issue and couldn't reproduce the problem
![ss-1642101598](https://user-images.githubusercontent.com/59485214/149395401-30562913-a6b1-4c9a-affa-abe523824a67.png)

Then I read this:
> can you tell which url is used egy.best is blocked by ISP - but egybest.org is ok

you see, `egy.best` is not actually the EgyBest website, it's just a site that takes you to one of the many EgyBest websites (e.g. `egybest.org`, `xena.egybest.ninja`, etc.), the actual EgyBest sites go up and down all the time, so they're not reliable, but `egy.best` is, because it always takes you to a website that is up; and that's what the script uses.

I see from your screenshot that you're probably using the egybest-cli.exe from the releases page, if you instead use the python script, you can change [the line that says](https://github.com/SafwanLjd/EgyBestCLI/blob/main/egybest-cli.py#L67):
```python
eb = EgyBest()
```
to
```python
eb = EgyBest("https://egybest.org")
```
and it will work for you, you can then compile this script yourself using [PyInstaller](https://www.pyinstaller.org/) to get the `.exe` version if you still want that.



There is another solution to your problem (it will only work if your ISP is blocking websites via DNS, odds are they probably do), which is using a custom DNS in your network settings, you can lookup "How to change the custom DNS in _Windows_", and then change it to something like 1.1.1.1 (Cloudflare) or 9.9.9.9 (Quad9).

The latter solution would unblock all the sites blocked by your ISP, which is a better solution if you ask me :)

**Comment by SafwanLjd** [comment]
@melbasuonyy 

Alright, I made a proper solution to your problem, download the [latest version](https://github.com/SafwanLjd/EgyBestCLI/releases/tag/v1.3) and edit the `C:\Users\mohde\.config\egybest\egybest-conf.json` file in your computer, and add the mirror  you want, similar to this:

```json
{
	"mirror": "https://egybest.org",

	"quality": {
		"2160": 1,
		"1080": 2,
		"720":  3,
		"480":  4,
		"360":  5,
		"240":  6
	}
}
```

Enjoy!
