### ISSUE TITLE
#suggestion# 

### ISSUE THREAD

**Issue by melbasuonyy** [SafwanLjd/EgyBestCLI#2]
First, Thanks you have put a great effort in this script,

I have 2 suggestions (if you don't mind)

Instead of downloading directly via cmd / the script why don't you export download links in csv file so it can be used in other download software like IDM 

second suggestion is full script tool for full website ( I know it will take time ) but it will be help full

additional : don't you thought of downloading full series instead of selecting each season 

Thanks

**Comment by SafwanLjd** [comment]
@melbasuonyy 

The script has a built in `--stdout/-o` option that you can use to do whatever you want via simple commands or short shell scripts of your own…

For example to export links to a file, you just need to run this command:

```bash
egybest-cli --title "Breaking Bad" --season 2 --stdout > links.txt
```
This will generate a `links.txt` file that has the links for all the episodes of the second season of the show "Breaking Bad" (one link per line), then you can use this file with whatever program you want… So the answer is no, I'm not going to explicitly implement this feature in the script because you can get the same behavior easily with simple shell "tricks", and this script being a CLI doesn't target novice computer users who aren't familiar with the terminal

As for the downloading a whole show instead of seasons, it can definitely be done, but this way it's better since if you don't provide a season, you perform an explicit movie search directly, which helps in getting correct results without asking the user if they meant the show or the movie, but again you can achieve this behavior easily by using a loop that goes from 1 (as in, season 1), and continues looping until it faces an error, which would be the script telling you that x season doesn't exist (meaning you downloaded all available seasons)… So, also no, I don't think I'm going to add this feature either


As for the "full script tool", it's out of this project's scope, this is a simple CLI, and it will always be a simple CLI… I do however, plan on using the [PyEgyBest](https://github.com/SafwanLjd/PyEgyBest) Library to make an EgyBest API, GUI, TUI, and maybe someday rewrite it in Dart and make an EgyBest mobile app with Flutter, but I'm not sure about the last part, especially since the guys working on [CloudStream-3](https://github.com/LagradOst/CloudStream-3) might [add support for it](https://github.com/LagradOst/CloudStream-3/issues/417), so it wouldn't make sense to make a worse version of their app; anyway it doesn't matter since I don't have enough time to make any of those at the moment.

Thanks for your suggestions though

P.S. I understand that you're on Windows, and from the screenshot on the last issue I see that you use CMD, You should probably use PowerShell instead, you should also check out [PowerShell Core](https://github.com/powershell/powershell), and [WindowsTerminal](https://www.microsoft.com/en-US/p/windows-terminal/9n0dx20hk701)… and consider adding your favorite video player to your `$PATH` to able to play episodes directly from it, e.g.

```powershell
# use PowerShell, won't work on CMD

# play the first episode of "Young Sheldon" in the VLC video player:
vlc $(egybest-cli -o -t "Young Sheldon" -s 1 -e 1)
```
